### PR TITLE
Fix parsing nullable collections

### LINKED ISSUE #163: Nullable collections throw RuntimeException
The following code throws `?array is not a collection`:

```php
(new TypeResolver())->resolve('?array<string, int>')
```

### LINKED ISSUE #3290: Error parsing nullable arrays in phpdoc
## Expected behavior

When using the shorthand nullable type syntax (`?T`) with an array in phpdoc, e.g.:

```php
/** 
 * @param ?array<string, string> $token
 */
public function setToken(?array $token = null): void { ... }
```
I expected this to result in `array<string, string>|null`.

The shorthand nullable type syntax _does_ work for simple types (e.g. `?int` -> `int|null`), which looks like it was added in v3.0.0 (https://github.com/phpDocumentor/phpDocumentor/issues/1833).

## Actual behavior

```
Unable to parse file "test.php", an error was detected: ?array is not a collection
```

## Your environment

* Version used: 3.3.1
* Install method: downloading the release with curl
* PHP version: 8.1.7
* Operating system and version (e.g. Ubuntu 20.04, Windows 10): 8.1.7-cli-alpine docker image
* Link to project build log: https://github.com/smrealms/smr/runs/7478051130?check_suite_focus=true

EDIT: Confirmed that this issue still exists in the dev version: `phpDocumentor vdev-master@52816d1`

### PR DESCRIPTION
**Pull request by hemberger**
Fixes #163.
Fixes phpDocumentor/phpDocumentor#3290.

Shorthand nullable type syntax is now supported for collection types
(e.g. `?array<int>`).

This also prevents a misuse of the shorthand nullable type syntax with
compound types, which is illegal with PHP types. This is documented in
the Union Types 2.0 RFC (https://wiki.php.net/rfc/union_types_v2) by
N. Popov:

> Union types and the ?T nullable type notation cannot be mixed.
> Writing ?T1|T2, T1|?T2 or ?(T1|T2) is not supported and T1|T2|null
> needs to be used instead.

### CODE REVIEW

File: tests/unit/TypeResolverTest.php [hunk 1]
```diff
@@ -407,9 +407,9 @@ public function testResolvingNullableCompoundTypes(): void
     {
         $fixture = new TypeResolver();
 
+        $this->expectException('RuntimeException');
+        $this->expectExceptionMessage('Unexpected type separator');
         $resolvedType = $fixture->resolve('?string|null|?boolean');
-
-        $this->assertSame('?string|null|?bool', (string) $resolvedType);
```
Comment (jaapio) [inline tests/unit/TypeResolverTest.php:412]: I'm not sure if this behavior should change. I do understand that PHP doesn't allow this format and that it looks more than ugly. But this case has been added because we found some repositories using this notation. 

As this library is used to parse types in docblocks and native PHP, I think we should keep this format supported. 
It could result in a deprecation that we will remove in the future. But for now, this is a backward compatibility break which we cannot do with the number of consuming projects for this library. 

Do you think it is possible to revert this change?

**Review by jaapio — CHANGES_REQUESTED** [review]

File: tests/unit/TypeResolverTest.php (hunk 1 above)
Comment (hemberger) [reply tests/unit/TypeResolverTest.php:412]: Thanks for the feedback! I did not fully appreciate the need for backwards compatibility, so I have restored support for shorthand nullable syntax in compound types as requested. Please let me know if this solution is not satisfactory.

**Review by jaapio — APPROVED** [review]
